### ISSUE TITLE
running a FEHM test

### ISSUE THREAD

**Issue by jbensabat** [lanl/FEHM#24]
Hello 
I have compiled FEHM under windows 10 and Intel Fortran.
I have created a dll and main program, which is basically mainrip_intel_dll.f (I guess its for intel compiler, having built the code as a dll).

the problem is that I do not see how to feed the data to the program
for example if I want to run the 1D_convection test case
I see three files in the input directory 
1D_Convection.dat
1D_Convection.files 
1D_Convection.grid 
 
I guess that the file that needs to be fed is 1D_convection.files 
can I hardcode the name of this file so I can run the code using the debugger ?
if yes where should I put it. 
What I see is that only the msim file (if it exists) is read in a way that is traceable. 

thanks for your help  

best
jac

**Comment by spchu** [comment]
I think you can change 1D_Convection.files to rename it as fehmn.files, the other two files will be linked in through fehmn.files
Leave all files in same folder as dll.

**Comment by jbensabat** [comment]
Hi 
thank you 
I figured it out. I had an error in the definition of the interface to FEHM.
since all variables are none initialized it did not pass correctly the value of method (which should have been zero)
now I can run the examples 
best
jac

**Comment by daniellivingston** [comment]
Great, glad you were able to fix it! I'm going to close this issue. If the problem reappears, feel free to re-open this issue.

Also, so that others in a similar situation may benefit, could you list more explicitly what you did to fix the issue?

**Comment by jbensabat** [comment]
Hi 
I am running FEHM using Intel Visual fortran. in the workspace properties you can choose to set all -uninitialized variables to 0 or not. I had a bug in the interface of subroutine FEHM which made the option variable uninitialized and non-zero. so the code went nowhere. once the passing argument problem resolved I had no problem running it.
