### ISSUE TITLE
Issue with tec_to_vtk.jl

### ISSUE THREAD

**Issue by CarlaRomano** [lanl/FEHM#33]
Hi I am trying to use the script for converting tecplot files to vtk for visualization in paraview.
I am experiences several issues. I have to say this is the second time I use julia, so I am not an expert about it.

The main bug is this line: elems = Array(MeshCell,numelems).
The error is: MethodError: no method matching Array(::Type{MeshCell}, ::Int64).
I guess this means that I can't create as it is, with Array, a vector populated with MeshCell for a number equal to numelems.

Any idea on how to solve this or an updated version of this code?

Thanks,
Carla

**Comment by daniellivingston** [comment]
Hi Carla, are you using [FEHM.jl](https://github.com/zemjulia/FEHM.jl) or is this code you wrote yourself?

**Comment by CarlaRomano** [comment]
Hi Daniel,
I found the tec_to_vtk.jl code in FEHM/tools of this [FEHM](https://github.com/lanl/FEHM
).
I am trying to use DfnWorks with FEHM. For what I understand there is no way to directly export the FEHM simulation results into a vtk file. This is why I was trying to use this julia code for converting the tecplot files to vtk.

**Comment by dharp** [comment]
Hi Carla,

I recently updated tec_to_vtk.jl to Julia 1.0, but that hasn’t made it into the master repo yet. I’m guessing you are using the script in the master repo? The updated one can be obtained here: https://github.com/lanl/FEHM/blob/SILO/tools/tec_to_vtk.jl

Dylan

**Comment by daniellivingston** [comment]
@dharp do you want me to update this repo with that script?

**Comment by dharp** [comment]
Yeah, that would be great!

**Comment by daniellivingston** [comment]
@dharp Okay, done! 

@CarlaRomano Can you pull the latest commit and let me know if it works? `master` is updated with the latest version of this script now.

**Comment by CarlaRomano** [comment]
Yes it works. I only had to specify in line 275 the name of the file containing the grid:  mesh = "full_mesh.fehmn"

Thank you so much!

**Comment by dharp** [comment]
Great! You can specify the mesh file with the “--mesh_file” cmdline option as well. It tries to read it from the fehm.files file if it exists in the folder otherwise.

Dylan

**Comment by daniellivingston** [comment]
Closing this for now. Re-open if there are any other issues!
