### ISSUE TITLE
Compiling on Apple Silicon (arm64)

### ISSUE THREAD

**Issue by vancesteven** [lanl/FEHM#45]
Under an M2 Mac with gfortran 13.2.0, make install returns this error:

src % make install
rm -f ./dated.f
rm -f ./dated.o
sed s/OS\ DATE/macOS\ 24-04-11/ ./dated.template > ./dated.f
gfortran -frecord-marker=4 -no-pie -march=native -O2 dated.f -c  -o ./dated.o
gfortran -frecord-marker=4 -no-pie -march=native -O2 enrich_ctr.f -c -o ./enrich_ctr.o
enrich_ctr.f:150:34:

  150 |          call add_resolution(1,ie,itype,nlayers,nei_add,node_add)
      |                                  1
Error: Rank mismatch in argument 'imtype' at (1) (scalar and rank-1)
make: *** [enrich_ctr.o] Error 1

**Comment by ehblackman** [comment]
I have this exact error as well. Windows 11, WSL2, GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by ehinrichs** [comment]
Thank you for bringing this to our attention. While I work on updating the repo, you can get around this error with the FFLAGS="-fallow-argument-mismatch" flag.

`make FFLAGS="-fallow-argument-mismatch"`
