### ISSUE TITLE
FEHMPYTEST log file not working with multiple failures

### ISSUE THREAD

**Issue by aidanstansberry** [lanl/FEHM#52]
Tested against a version of FEHM that passed 14/17 tests. However, not all of the failure messages got written in the log file. In my case three cases failed (dissolution, doe, and dryout) and only the error message from dryout was written. However, all of the errors were written to screen, so probably just a small bug.

**Comment by ehinrichs** [comment]
Thank you for letting us know! I've pushed an update to master that should fix the issue.
