### ISSUE TITLE
fehmpytests fails boun

### ISSUE THREAD

**Issue by millerta** [lanl/FEHM#74]
The fehmpytests compare files fail, reason to be determined.
Output needs to be checked against VV version and also between win and linux.

**Comment by millerta** [comment]
This test runs correctly outside of the scripts. The windows and linux results are the same within precision.
There are 3 tests, 1, 2, and 3. But fehmpytests only run the first.

This is the output from fehmpytests:
```
python fehmpytests.py /project/eesdev/FEHM/FEHM_FORK/FEHM_gaz-linux/src_release/xfehm boun

boun (__main__.fehmTest.boun)
**Test the Boundry Functionality** ... FAIL

======================================================================
FAIL: boun (__main__.fehmTest.boun)
**Test the Boundry Functionality**
----------------------------------------------------------------------
AssertionError: False is not true : Incorrect Hydraulic Head (m) at time 2.0.
----------------------------------------------------------------------
Ran 1 test in 3.177s
FAILED (failures=1)
```

Only one directory was created.
Files differ but are within the precision used to compare results in the WIN and lnx VV Test Suites.
```
diff prob_well_boun1_output/prob_well_boun1.00002_sca_node.avs compare/prob_well_boun1.00002_sca_node.avs
< 0000007055   950.000000    1000.00000    0.00000000    2.05773429    200.003512
< 0000007056   1000.00000    1000.00000    0.00000000    2.05770036    200.000046
---
> 0000007055   950.000000    1000.00000    0.00000000    2.05773440    200.003523
> 0000007056   1000.00000    1000.00000    0.00000000    2.05769991    200.000000
```

**Comment by xiang112233** [comment]
def boun(self): 
        """
        **Test the Boundry Functionality**
        
        Compares the generated contour files to old contour files that are known
        to be correct. Only the pressure and hydraulic head values at time 2 are 
        tested.
        
fixed

```
        .. Authors: Mark Lange
        .. Updated: June 2014 by Mark Lange
        """
        
        arguments = {}
        arguments['times'] = [2.0]
        arguments['variables'] = ['P', 'H']

        self.test_case('boun', arguments) 
```

**Comment by millerta** [comment]
This test now succeeds on Linux and windows.
